# Generated by Django 3.1.2 on 2020-10-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreammingNvideo',
            fields=[
                ('nvideo', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'streamming_nvideo',
                'managed': False,
            },
        ),
    ]
